name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go env
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./cmd/diligent-parrot/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
